package com.atomguard.velocity.module.bedrock;

import com.atomguard.velocity.AtomGuardVelocity;
import com.atomguard.velocity.config.VelocityConfigManager;
import com.velocitypowered.api.proxy.ProxyServer;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.slf4j.Logger;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.anyBoolean;
import static org.mockito.ArgumentMatchers.anyDouble;
import static org.mockito.ArgumentMatchers.anyInt;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.lenient;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
class BedrockSupportModuleTest {

    @Mock private AtomGuardVelocity plugin;
    @Mock private VelocityConfigManager configManager;
    @Mock private ProxyServer proxyServer;
    @Mock private Logger logger;

    @BeforeEach
    void setUp() {
        lenient().when(plugin.getSlf4jLogger()).thenReturn(logger);
        lenient().when(plugin.getConfigManager()).thenReturn(configManager);
        lenient().when(plugin.getProxyServer()).thenReturn(proxyServer);
    }

    // ================================================================
    // BedrockBotDetector tests (standalone, no Bukkit/Velocity deps)
    // ================================================================

    @Nested
    class BotDetectorTests {

        private BedrockBotDetector detector;

        @BeforeEach
        void setUp() {
            detector = new BedrockBotDetector(plugin);
        }

        @Test
        void nullBrandIncreasesScore() {
            int score = detector.evaluateThreat("127.0.0.1", ".TestPlayer", null);
            assertThat(score).isGreaterThanOrEqualTo(30);
        }

        @Test
        void blankBrandIncreasesScore() {
            int score = detector.evaluateThreat("127.0.0.1", ".TestPlayer", "   ");
            assertThat(score).isGreaterThanOrEqualTo(30);
        }

        @Test
        void geyserBrandDoesNotAddBrandPenalty() {
            int score = detector.evaluateThreat("127.0.0.1", ".TestPlayer", "Geyser");
            // No brand penalty (30), no connection flooding, no pattern match
            assertThat(score).isEqualTo(0);
        }

        @Test
        void bedrockBrandDoesNotAddBrandPenalty() {
            int score = detector.evaluateThreat("127.0.0.1", ".TestPlayer", "Bedrock");
            assertThat(score).isEqualTo(0);
        }

        @Test
        void unknownBrandAdds10() {
            int score = detector.evaluateThreat("127.0.0.1", ".TestPlayer", "UnknownClient");
            assertThat(score).isEqualTo(10);
        }

        @Test
        void multipleConnectionsFromSameIpIncreasesScore() {
            String ip = "192.168.1.1";
            // First 5 connections do not add connection penalty
            for (int i = 0; i < 5; i++) {
                detector.evaluateThreat(ip, ".Player" + i, "Geyser");
            }
            // 6th connection should trigger the connection count penalty
            int score = detector.evaluateThreat(ip, ".Player6", "Geyser");
            assertThat(score).isGreaterThan(0);
        }

        @Test
        void autoGeneratedUsernamePatternAdds15() {
            // Pattern: starts with ".", 3+ letters, 4+ digits
            int score = detector.evaluateThreat("10.0.0.1", ".Abc1234", "Geyser");
            assertThat(score).isEqualTo(15);
        }

        @Test
        void normalBedrockUsernameDoesNotMatchPattern() {
            // Normal bedrock name that does not match the auto-generated pattern
            int score = detector.evaluateThreat("10.0.0.1", ".Steve", "Geyser");
            assertThat(score).isEqualTo(0);
        }

        @Test
        void scoreCappedAt100() {
            String ip = "10.0.0.2";
            // Force many connections + null brand + auto-generated name
            for (int i = 0; i < 50; i++) {
                detector.evaluateThreat(ip, ".Abc1234", null);
            }
            int score = detector.evaluateThreat(ip, ".Abc1234", null);
            assertThat(score).isLessThanOrEqualTo(100);
        }

        @Test
        void cleanupResetsConnectionCounts() {
            String ip = "10.0.0.3";
            for (int i = 0; i < 10; i++) {
                detector.evaluateThreat(ip, ".Player" + i, "Geyser");
            }
            detector.cleanup();

            // After cleanup, the first connection should not have connection count penalty
            int score = detector.evaluateThreat(ip, ".NewPlayer", "Geyser");
            assertThat(score).isEqualTo(0);
        }
    }

    // ================================================================
    // BedrockSupportModule config and detection tests
    // ================================================================

    @Nested
    class ModuleConfigTests {

        private BedrockSupportModule module;

        @BeforeEach
        void setUp() {
            // Config stubs for module constructor and enable
            lenient().when(configManager.getBoolean(eq("moduller.bedrock-destek.aktif"), anyBoolean())).thenReturn(true);
            lenient().when(configManager.getString(eq("moduller.bedrock-destek.bedrock-prefix"), anyString())).thenReturn(".");
            lenient().when(configManager.getInt(eq("moduller.bedrock-destek.xbox-live-bonus"), anyInt())).thenReturn(10);
            lenient().when(configManager.getDouble(eq("moduller.bedrock-destek.bedrock-rate-limit-carpani"), anyDouble())).thenReturn(1.5);
            lenient().when(configManager.getBoolean(eq("moduller.bedrock-destek.floodgate-entegrasyon"), anyBoolean())).thenReturn(false);

            module = new BedrockSupportModule(plugin);
        }

        @Test
        void moduleCreatedSuccessfully() {
            assertThat(module).isNotNull();
            assertThat(module.getName()).isEqualTo("bedrock-destek");
        }

        @Test
        void moduleIsNotEnabledByDefault() {
            // Before enable() is called
            assertThat(module.isEnabled()).isFalse();
        }

        @Test
        void bedrockDetectionByPrefixIsHandledByBotDetector() {
            // The bot detector component works standalone
            BedrockBotDetector botDetector = module.getBotDetector();
            assertThat(botDetector).isNotNull();
        }

        @Test
        void xboxBonusDefaultIs10() {
            // Module needs to be enabled to read config values into fields
            var eventManager = org.mockito.Mockito.mock(com.velocitypowered.api.event.EventManager.class);
            when(proxyServer.getEventManager()).thenReturn(eventManager);
            module.enable();

            assertThat(module.getXboxLiveBonus()).isEqualTo(10);
        }

        @Test
        void rateLimitMultiplierDefaultIs1_5() {
            var eventManager = org.mockito.Mockito.mock(com.velocitypowered.api.event.EventManager.class);
            when(proxyServer.getEventManager()).thenReturn(eventManager);
            module.enable();

            assertThat(module.getRateLimitMultiplier()).isEqualTo(1.5);
        }

        @Test
        void isBedrockPlayerReturnsFalseForUnknownIp() {
            var eventManager = org.mockito.Mockito.mock(com.velocitypowered.api.event.EventManager.class);
            when(proxyServer.getEventManager()).thenReturn(eventManager);
            module.enable();

            assertThat(module.isBedrockPlayer("1.2.3.4")).isFalse();
        }

        @Test
        void floodgateIntegrationIsNotNull() {
            assertThat(module.getFloodgate()).isNotNull();
        }

        @Test
        void handshakeValidatorIsNotNull() {
            assertThat(module.getHandshakeValidator()).isNotNull();
        }
    }

    // ================================================================
    // Bedrock detection by username prefix (unit-level logic)
    // ================================================================

    @Nested
    class PrefixDetectionTests {

        @Test
        void dotPrefixIndicatesBedrockPlayer() {
            String bedrockPrefix = ".";
            String username = ".BedrockPlayer123";
            assertThat(username.startsWith(bedrockPrefix)).isTrue();
        }

        @Test
        void noPrefixIndicatesJavaPlayer() {
            String bedrockPrefix = ".";
            String username = "JavaPlayer123";
            assertThat(username.startsWith(bedrockPrefix)).isFalse();
        }

        @Test
        void customPrefixDetection() {
            String bedrockPrefix = "*";
            String username = "*CustomBedrock";
            assertThat(username.startsWith(bedrockPrefix)).isTrue();
        }
    }
}
