name: AtomGuard
version: '${project.version}'
main: com.atomguard.AtomGuard
api-version: '1.21'
description: "Advanced exploit protection and server security for Minecraft"
author: AtomGuard Team
website: "https://atomguard.dev"
depend:
  - packetevents
softdepend:
  - AuthMe
  - nLogin

commands:
  atomguard:
    description: "AtomGuard main command"
    usage: "/<command> [reload|status|toggle|stats|info|health]"
    permission: atomguard.admin
    aliases: [ag]
  panic:
    description: "Enable panic mode during bot attacks"
    usage: "/<command>"
    permission: atomguard.panic
    aliases: [panik]

permissions:
  atomguard.admin:
    description: "Access to all AtomGuard commands"
    default: op
  atomguard.bypass:
    description: "Bypass all exploit checks"
    default: false
  atomguard.reload:
    description: "Permission to reload config"
    default: op
  atomguard.notify:
    description: "Receive exploit notifications"
    default: op
  atomguard.panic:
    description: "Permission to use panic mode"
    default: op